### ISSUE TITLE
发送查看没有反应

### ISSUE THREAD

**Issue by Kimaru-bili** [bridgeL/nonebot-plugin-ayaka-scan-cmd#1]
后台显示报了个错
![image](https://user-images.githubusercontent.com/40233772/213745525-959b5614-4e63-4816-9a1b-84659717b7df.png)
![image](https://user-images.githubusercontent.com/40233772/213745327-2825aa8e-0d10-4601-90c1-55c32c09434a.png)

**Comment by bridgeL** [comment]
ayaka更新以后忘了这老伙计了，等我0.0.5版本修一下吧

**Comment by bridgeL** [comment]
已更新

**Comment by Kimaru-bili** [comment]
好的，麻烦了😉
